#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinNativeDemo.Droid.Resource", IsApplication=true)]

namespace XamarinNativeDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.RangeSlider.Resource.Attribute.absoluteMaxValue = global::XamarinNativeDemo.Droid.Resource.Attribute.absoluteMaxValue;
			global::Xamarin.RangeSlider.Resource.Attribute.absoluteMinValue = global::XamarinNativeDemo.Droid.Resource.Attribute.absoluteMinValue;
			global::Xamarin.RangeSlider.Resource.Attribute.activateOnDefaultValues = global::XamarinNativeDemo.Droid.Resource.Attribute.activateOnDefaultValues;
			global::Xamarin.RangeSlider.Resource.Attribute.activeColor = global::XamarinNativeDemo.Droid.Resource.Attribute.activeColor;
			global::Xamarin.RangeSlider.Resource.Attribute.alwaysActive = global::XamarinNativeDemo.Droid.Resource.Attribute.alwaysActive;
			global::Xamarin.RangeSlider.Resource.Attribute.barHeight = global::XamarinNativeDemo.Droid.Resource.Attribute.barHeight;
			global::Xamarin.RangeSlider.Resource.Attribute.defaultColor = global::XamarinNativeDemo.Droid.Resource.Attribute.defaultColor;
			global::Xamarin.RangeSlider.Resource.Attribute.internalPadding = global::XamarinNativeDemo.Droid.Resource.Attribute.internalPadding;
			global::Xamarin.RangeSlider.Resource.Attribute.materialUI = global::XamarinNativeDemo.Droid.Resource.Attribute.materialUI;
			global::Xamarin.RangeSlider.Resource.Attribute.maxThumbHidden = global::XamarinNativeDemo.Droid.Resource.Attribute.maxThumbHidden;
			global::Xamarin.RangeSlider.Resource.Attribute.minThumbHidden = global::XamarinNativeDemo.Droid.Resource.Attribute.minThumbHidden;
			global::Xamarin.RangeSlider.Resource.Attribute.showRangeLabels = global::XamarinNativeDemo.Droid.Resource.Attribute.showRangeLabels;
			global::Xamarin.RangeSlider.Resource.Attribute.stepValue = global::XamarinNativeDemo.Droid.Resource.Attribute.stepValue;
			global::Xamarin.RangeSlider.Resource.Attribute.stepValueContinuously = global::XamarinNativeDemo.Droid.Resource.Attribute.stepValueContinuously;
			global::Xamarin.RangeSlider.Resource.Attribute.textAboveThumbsColor = global::XamarinNativeDemo.Droid.Resource.Attribute.textAboveThumbsColor;
			global::Xamarin.RangeSlider.Resource.Attribute.textSize = global::XamarinNativeDemo.Droid.Resource.Attribute.textSize;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbDisabled = global::XamarinNativeDemo.Droid.Resource.Attribute.thumbDisabled;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbNormal = global::XamarinNativeDemo.Droid.Resource.Attribute.thumbNormal;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbPressed = global::XamarinNativeDemo.Droid.Resource.Attribute.thumbPressed;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadow = global::XamarinNativeDemo.Droid.Resource.Attribute.thumbShadow;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadowBlur = global::XamarinNativeDemo.Droid.Resource.Attribute.thumbShadowBlur;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadowColor = global::XamarinNativeDemo.Droid.Resource.Attribute.thumbShadowColor;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadowXOffset = global::XamarinNativeDemo.Droid.Resource.Attribute.thumbShadowXOffset;
			global::Xamarin.RangeSlider.Resource.Attribute.thumbShadowYOffset = global::XamarinNativeDemo.Droid.Resource.Attribute.thumbShadowYOffset;
			global::Xamarin.RangeSlider.Resource.Attribute.valuesAboveThumbs = global::XamarinNativeDemo.Droid.Resource.Attribute.valuesAboveThumbs;
			global::Xamarin.RangeSlider.Resource.String.app_name = global::XamarinNativeDemo.Droid.Resource.String.app_name;
			global::Xamarin.RangeSlider.Resource.String.demo_max_label = global::XamarinNativeDemo.Droid.Resource.String.demo_max_label;
			global::Xamarin.RangeSlider.Resource.String.demo_min_label = global::XamarinNativeDemo.Droid.Resource.String.demo_min_label;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_absoluteMaxValue = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_absoluteMaxValue;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_absoluteMinValue = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_absoluteMinValue;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_activateOnDefaultValues = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_activateOnDefaultValues;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_activeColor = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_activeColor;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_alwaysActive = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_alwaysActive;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_barHeight = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_barHeight;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_defaultColor = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_defaultColor;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_internalPadding = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_internalPadding;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_materialUI = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_materialUI;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_maxThumbHidden = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_maxThumbHidden;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_minThumbHidden = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_minThumbHidden;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_showRangeLabels = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_showRangeLabels;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_stepValue = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_stepValue;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_stepValueContinuously = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_stepValueContinuously;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_textAboveThumbsColor = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_textAboveThumbsColor;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_textSize = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_textSize;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbDisabled = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_thumbDisabled;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbNormal = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_thumbNormal;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbPressed = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_thumbPressed;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadow = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_thumbShadow;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadowBlur = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_thumbShadowBlur;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadowColor = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_thumbShadowColor;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadowXOffset = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_thumbShadowXOffset;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_thumbShadowYOffset = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_thumbShadowYOffset;
			global::Xamarin.RangeSlider.Resource.Styleable.RangeSliderControl_valuesAboveThumbs = global::XamarinNativeDemo.Droid.Resource.Styleable.RangeSliderControl_valuesAboveThumbs;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int absoluteMaxValue = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int absoluteMinValue = 2130771968;
			
			// aapt resource value: 0x7f010014
			public const int activateOnDefaultValues = 2130771988;
			
			// aapt resource value: 0x7f01000a
			public const int activeColor = 2130771978;
			
			// aapt resource value: 0x7f010005
			public const int alwaysActive = 2130771973;
			
			// aapt resource value: 0x7f010008
			public const int barHeight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int defaultColor = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int internalPadding = 2130771975;
			
			// aapt resource value: 0x7f010018
			public const int materialUI = 2130771992;
			
			// aapt resource value: 0x7f010003
			public const int maxThumbHidden = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int minThumbHidden = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int showRangeLabels = 2130771972;
			
			// aapt resource value: 0x7f010015
			public const int stepValue = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int stepValueContinuously = 2130771990;
			
			// aapt resource value: 0x7f01000b
			public const int textAboveThumbsColor = 2130771979;
			
			// aapt resource value: 0x7f010017
			public const int textSize = 2130771991;
			
			// aapt resource value: 0x7f01000e
			public const int thumbDisabled = 2130771982;
			
			// aapt resource value: 0x7f01000c
			public const int thumbNormal = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int thumbPressed = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int thumbShadow = 2130771983;
			
			// aapt resource value: 0x7f010013
			public const int thumbShadowBlur = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int thumbShadowColor = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int thumbShadowXOffset = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int thumbShadowYOffset = 2130771986;
			
			// aapt resource value: 0x7f010006
			public const int valuesAboveThumbs = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int black = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int lightBlue = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int light_grey = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int main = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int materialGrey = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int red = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int splash_background = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int white = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int layout_border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int single_border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int solid_shape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int splash_200 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splash_screen = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000f
			public const int btnCalculate = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int btnCloseDialog = 2131296273;
			
			// aapt resource value: 0x7f09000e
			public const int btnCustomsCleared = 2131296270;
			
			// aapt resource value: 0x7f090016
			public const int btnSelectYear = 2131296278;
			
			// aapt resource value: 0x7f090014
			public const int doubleModeSwitch = 2131296276;
			
			// aapt resource value: 0x7f090018
			public const int item_menu_refresh = 2131296280;
			
			// aapt resource value: 0x7f090013
			public const int pickerList = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int pickerSearch = 2131296274;
			
			// aapt resource value: 0x7f090010
			public const int pickerTitle = 2131296272;
			
			// aapt resource value: 0x7f090015
			public const int rangeSlider = 2131296277;
			
			// aapt resource value: 0x7f09000d
			public const int rowCustomsCleared = 2131296269;
			
			// aapt resource value: 0x7f090007
			public const int rowEngineVolume = 2131296263;
			
			// aapt resource value: 0x7f09000b
			public const int rowFuelType = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int rowGearBox = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int rowMarks = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int rowModels = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int rowYear = 2131296261;
			
			// aapt resource value: 0x7f090000
			public const int toolbar = 2131296256;
			
			// aapt resource value: 0x7f090017
			public const int toolbar_title = 2131296279;
			
			// aapt resource value: 0x7f090008
			public const int txtEngineVolume = 2131296264;
			
			// aapt resource value: 0x7f09000c
			public const int txtFuelType = 2131296268;
			
			// aapt resource value: 0x7f09000a
			public const int txtGearBox = 2131296266;
			
			// aapt resource value: 0x7f090002
			public const int txtMark = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int txtModel = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int txtYear = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int PickerLayout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int RangeLayout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Toolbar = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int right_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int close = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Icon = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int refresh = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050021
			public const int calculate = 2131034145;
			
			// aapt resource value: 0x7f050003
			public const int cancel = 2131034115;
			
			// aapt resource value: 0x7f050028
			public const int customs_cleared = 2131034152;
			
			// aapt resource value: 0x7f050002
			public const int demo_max_label = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int demo_min_label = 2131034113;
			
			// aapt resource value: 0x7f05002e
			public const int double_mode = 2131034158;
			
			// aapt resource value: 0x7f050027
			public const int engine_volume = 2131034151;
			
			// aapt resource value: 0x7f050007
			public const int exit = 2131034119;
			
			// aapt resource value: 0x7f050024
			public const int fuel_type = 2131034148;
			
			// aapt resource value: 0x7f05002d
			public const int gear_box_type = 2131034157;
			
			// aapt resource value: 0x7f050023
			public const int gearbox = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int mark = 2131034149;
			
			// aapt resource value: 0x7f05000d
			public const int message_check_connection = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int message_loading = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int message_loading_error = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int message_no_connection = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int message_not_include = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int message_refresh = 2131034129;
			
			// aapt resource value: 0x7f050022
			public const int model = 2131034146;
			
			// aapt resource value: 0x7f050006
			public const int no = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int ok = 2131034116;
			
			// aapt resource value: 0x7f050031
			public const int result_error = 2131034161;
			
			// aapt resource value: 0x7f050030
			public const int result_not_found = 2131034160;
			
			// aapt resource value: 0x7f050032
			public const int result_template = 2131034162;
			
			// aapt resource value: 0x7f05002f
			public const int result_title = 2131034159;
			
			// aapt resource value: 0x7f050008
			public const int search_text = 2131034120;
			
			// aapt resource value: 0x7f050029
			public const int select = 2131034153;
			
			// aapt resource value: 0x7f05002b
			public const int select_mark = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int select_model = 2131034154;
			
			// aapt resource value: 0x7f05002c
			public const int select_year = 2131034156;
			
			// aapt resource value: 0x7f050009
			public const int selector_tag = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int title_delete = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int title_error = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int title_info = 2131034123;
			
			// aapt resource value: 0x7f050026
			public const int year = 2131034150;
			
			// aapt resource value: 0x7f050005
			public const int yes = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int автомат = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int адаптивная = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int бензин = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int вариатор = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int газ = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int газ_бензин = 2131034139;
			
			// aapt resource value: 0x7f05001f
			public const int газ_метан = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int газ_пропан_бутан = 2131034144;
			
			// aapt resource value: 0x7f05001c
			public const int гибрид = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int дизель = 2131034137;
			
			// aapt resource value: 0x7f05001e
			public const int другое = 2131034142;
			
			// aapt resource value: 0x7f050013
			public const int ручная_механика = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int типтроник = 2131034133;
			
			// aapt resource value: 0x7f05001d
			public const int электро = 2131034141;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int mainTheme = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int mainTheme_Splash = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int dialogStyle = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int pickerStyle = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int searchViewStyle = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int switchStyle = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RangeSliderControl = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 1
			public const int RangeSliderControl_absoluteMaxValue = 1;
			
			// aapt resource value: 0
			public const int RangeSliderControl_absoluteMinValue = 0;
			
			// aapt resource value: 20
			public const int RangeSliderControl_activateOnDefaultValues = 20;
			
			// aapt resource value: 10
			public const int RangeSliderControl_activeColor = 10;
			
			// aapt resource value: 5
			public const int RangeSliderControl_alwaysActive = 5;
			
			// aapt resource value: 8
			public const int RangeSliderControl_barHeight = 8;
			
			// aapt resource value: 9
			public const int RangeSliderControl_defaultColor = 9;
			
			// aapt resource value: 7
			public const int RangeSliderControl_internalPadding = 7;
			
			// aapt resource value: 24
			public const int RangeSliderControl_materialUI = 24;
			
			// aapt resource value: 3
			public const int RangeSliderControl_maxThumbHidden = 3;
			
			// aapt resource value: 2
			public const int RangeSliderControl_minThumbHidden = 2;
			
			// aapt resource value: 4
			public const int RangeSliderControl_showRangeLabels = 4;
			
			// aapt resource value: 21
			public const int RangeSliderControl_stepValue = 21;
			
			// aapt resource value: 22
			public const int RangeSliderControl_stepValueContinuously = 22;
			
			// aapt resource value: 11
			public const int RangeSliderControl_textAboveThumbsColor = 11;
			
			// aapt resource value: 23
			public const int RangeSliderControl_textSize = 23;
			
			// aapt resource value: 14
			public const int RangeSliderControl_thumbDisabled = 14;
			
			// aapt resource value: 12
			public const int RangeSliderControl_thumbNormal = 12;
			
			// aapt resource value: 13
			public const int RangeSliderControl_thumbPressed = 13;
			
			// aapt resource value: 15
			public const int RangeSliderControl_thumbShadow = 15;
			
			// aapt resource value: 19
			public const int RangeSliderControl_thumbShadowBlur = 19;
			
			// aapt resource value: 16
			public const int RangeSliderControl_thumbShadowColor = 16;
			
			// aapt resource value: 17
			public const int RangeSliderControl_thumbShadowXOffset = 17;
			
			// aapt resource value: 18
			public const int RangeSliderControl_thumbShadowYOffset = 18;
			
			// aapt resource value: 6
			public const int RangeSliderControl_valuesAboveThumbs = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
